FROM node:14-alpine

RUN apk --no-cache add git
RUN git clone https://github.com/MCSManager/MCSManager-Web-Production /opt/docker-mcsm/web
RUN cd /opt/docker-mcsm/web && npm i --production

ENV TZ=Asia/Shanghai

EXPOSE 23333

WORKDIR /opt/docker-mcsm/web

ENTRYPOINT [ "node", "app.js" ]
