FROM node:14-alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && apk update && apk add git
RUN git clone https://github.com/MCSManager/MCSManager-Daemon-Production /opt/mcsmanager/daemon --depth=1
RUN cd /opt/mcsmanager/daemon && npm i --production

RUN mkdir -p /opt/mcsmanager/web/data

ENV TZ=Asia/Shanghai

VOLUME [ "/opt/mcsmanager/web/data" ]

EXPOSE 23333

WORKDIR /opt/mcsmanager/web

ENTRYPOINT [ "node", "app.js" ]
