name: Get latest MCSM version (Daemon)

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_GITHUB_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/MCSManager/Daemon/releases/latest | \
          jq -r ".tag_name" > release-versions/mcsm-daemon-version.txt
      - name: Check for modified files
        id: git-check
        run: (echo modified=$([ -z "`git status --porcelain`" ] >> $GITHUB_OUTPUT) && echo "false" || echo "true")
      - name: Get current version file content
        run: cat release-versions/mcsm-daemon-version.txt
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git commit -am "chore: new release version (daemon)"
          git push
