name: Build and Publish Docker Image (Daemon)

on:
  push:
    paths:
      - "release-versions/mcsm-version-daemon.txt"
  workflow_dispatch:

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v3

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v2

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2

      - name: Read Version file
        id: getversion
        run: echo "version=$(cat release-versions/mcsm-version-daemon.txt)" >> $GITHUB_OUTPUT

      - name: "Run build docker script"
        run: ./build-docker-daemon.sh ${{ steps.getversion.outputs.version }}

      - name: "Login to Docker Hub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Push image to Docker Hub"
        run: ./push-docker-daemon.sh ${{ steps.getversion.outputs.version }} ${{ secrets.DOCKERHUB_USERNAME }}
